### PR TITLE
fixup! Use the system protobuf.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This reduces the amount of churn vs master, keeps expected forwarding aliases and conventional names intact, and works with both Drake on Ubuntu and TRI-internal users.  Not tested on macOS.

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
FYI @clalancette @jamiesnape

**Comment by clalancette** [comment]
This looks fine to me.  There's some minor buildifier warnings with the code, but that's easy enough to fix up.  @jamiesnape, if you are OK with this, I'll merge this into the `use-libprotobuf` branch.

**Comment by jamiesnape** [comment]
Yes, I think it is good.

**Comment by jwnimmer-tri** [comment]
Ah, yeah; sorry about the lint.  I was switching workspaces a lot and missed that.

**Comment by clalancette** [comment]
> Ah, yeah; sorry about the lint. I was switching workspaces a lot and missed that.

No worries; I've fixed it on the `use-libprotobuf` branch now.

**Pull request merged**
