### PR TITLE
use latest Drakes' pybind11 version to get support for moving unique pointers

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Use a fork of pybind that supports std::move'ing unique_pointers.
Required by https://github.com/ToyotaResearchInstitute/delphyne/pull/177

### CODE REVIEW

**Comment by basicNew** [comment]
@clalancette I'm ok with this, as we need it to support our python demos.

**Comment by clalancette** [comment]
It looks like upstream commit https://github.com/RobotLocomotion/drake/commit/39ed50ec769b598da8b892f0d1e1ad476f4ece65 changed this to a different RobotLocomotion/pybind11 commit.  Can we follow that, or do we still need to use Eric's fork?

**Comment by mikaelarguedas** [comment]
We should be able to follow that now. The [commit we needed](https://github.com/RobotLocomotion/pybind11/commit/48999b69bde29cdf8d616d4fbd3d6ab1c561027d) has been merged. So if we're ready to track drake master we can close this PR, otherwise I can update it to use the same commit hash as Drake

**Comment by clalancette** [comment]
We are almost, but not quite, ready to switch to drake master.  Drake upstream switched the directory layout around, so we need some changes to delphyne and delphyne-gui, which I have in branches https://github.com/ToyotaResearchInstitute/delphyne/tree/drake-master and https://github.com/ToyotaResearchInstitute/delphyne-gui/tree/drake-master .  Unfortunately, those changes aren't quite enough.  When trying to do the cmake configure step in delphyne, I get:

```
CMake Error at backend/CMakeLists.txt:63 (add_library):
  Target "simulation_runner_py" links to target "Boost::boost" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

I'm guessing that somehow the cmake dependencies changed, but I'm not quite sure how to make it work.  I don't quite have time to look into that today, so we can either just do the cherry-pick of the commit you need for now, or you can look into the Boost problem if you have time.

**Comment by mikaelarguedas** [comment]
> so we can either just do the cherry-pick of the commit you need for now, or you can look into the Boost problem if you have time.

I'm on vacation this week so I won't look into it. Though I'm surprised as there is no library linking against Boost in delphyne anymore, that's actually the reason we need this commit (to be able to get rid of Boost completly on the AutomotiveSimulatorPort as well).

I updated this PR to use the pybind commit we need to get https://github.com/ToyotaResearchInstitute/delphyne/pull/177 merged.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
