### PR TITLE
Pybind11 CMake fixups

### PR DESCRIPTION
**Pull request by mikaelarguedas**
pybind11 defines a custom module for finding Python libraries.
Their CMake Config file adds it to the CMAKE_EMODULE_PATH for visibility. 
https://github.com/RobotLocomotion/pybind11/blob/ffcf754ae9e766632610975d22372a86a7b63014/tools/pybind11Config.cmake.in#L73-L74

This PR update the pcs configuration to do the same.
This is necessary for downstream packages to be able to `find_package` pybind11.

@clalancette I targeted the branch used in the repos file, but can target another one if it's more appropriate

@basicNew  FYI

Connects to ToyotaResearchInstitute/delphyne#169

### CODE REVIEW

**Comment by clalancette** [comment]
I think we should target this to upstream Drake master to start with; once it is in there, we can cherry-pick it onto this branch.  I'm happy to help getting it into upstream Drake (as there is a bit of process there); just let me know if you need help.

**Comment by mikaelarguedas** [comment]
Sounds good to me.
A pointer to the process description would be appreciated if it's not trivial to find

**Comment by clalancette** [comment]
http://drake.mit.edu/developers.html#code-review is a good overview of the process.

**Comment by mikaelarguedas** [comment]
closing in favor of https://github.com/RobotLocomotion/drake/pull/7641 submitted upstream

**Pull request closed without merging**
